language: cpp
os: linux
compiler:
  - clang
  - gcc

script:
  - git clone https://github.com/KhronosGroup/Vulkan-Docs
  - cc -c volk.c -Wall -Wextra -Werror -IVulkan-Docs/include # check Vulkan 1.1 build
  - git -C Vulkan-Docs checkout ab08f0951ef1ad9b84db93f971e113c1d9d55609 # last 1.0 rev
  - cc -c volk.c -Wall -Wextra -Werror -IVulkan-Docs/src # check Vulkan 1.0 build
