language: cpp
os: linux
compiler:
  - clang
  - gcc

env:
  - SPEC_REV=ce60b9c88745ecded74296dfbe69dae7c1fb2e62

script:
  - git clone https://github.com/KhronosGroup/Vulkan-Docs
  - git -C Vulkan-Docs checkout $SPEC_REV
  - ./generate.py Vulkan-Docs/src/spec/vk.xml
  - git diff --exit-code # make sure output matches repo contents
  - cc -c volk.c -Wall -Wextra -Werror -IVulkan-Docs/src # check Vulkan 1.1 build
  - git -C Vulkan-Docs checkout ab08f0951ef1ad9b84db93f971e113c1d9d55609
  - cc -c volk.c -Wall -Wextra -Werror -IVulkan-Docs/src # check Vulkan 1.0 build
