language: cpp
os:
  - linux
  - osx
  - windows

script:
  - git clone https://github.com/KhronosGroup/Vulkan-Headers
  - export VULKAN_SDK=./Vulkan-Headers
  - mkdir build
  - mkdir installed
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../installed ..
  - cmake --build .
  - cmake --install .